### ISSUE TITLE
Fails on Windows 11 Pro

### ISSUE THREAD

**Issue by huyz** [informatique-cdc/ansible-role-win_authorized_key#3]
**Describe the bug**
Trying to run it, I get:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 733
fatal: [myhost]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: The term 'Repair-AuthorizedKeyPermission' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
```

**To Reproduce**
```
roles:
    - informatiquecdc.win_authorized_key
 vars:
    pub_file_for_ssh: ~/.ssh/id_ed25519.pub

tasks:
    - name: Add to authorized_keys the content of {{ pub_file_for_ssh }}
      win_authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', pub_file_for_ssh) }}"
```

**Additional context**

I believe this may be due to OpenSSHUtils being deprecated; see https://github.com/MicrosoftDocs/windowsserverdocs/pull/4788#issuecomment-687662994
